// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/femR.h"
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif


RcppExport SEXP _rcpp_module_boot_cpp_lagrange_basis_2d_fe1();
RcppExport SEXP _rcpp_module_boot_cpp_lagrange_basis_2d_fe2();
RcppExport SEXP _rcpp_module_boot_cpp_2d_domain();
RcppExport SEXP _rcpp_module_boot_cpp_pde_2d_fe1();
RcppExport SEXP _rcpp_module_boot_cpp_pde_2d_fe2();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_cpp_lagrange_basis_2d_fe1", (DL_FUNC) &_rcpp_module_boot_cpp_lagrange_basis_2d_fe1, 0},
    {"_rcpp_module_boot_cpp_lagrange_basis_2d_fe2", (DL_FUNC) &_rcpp_module_boot_cpp_lagrange_basis_2d_fe2, 0},
    {"_rcpp_module_boot_cpp_2d_domain", (DL_FUNC) &_rcpp_module_boot_cpp_2d_domain, 0},
    {"_rcpp_module_boot_cpp_pde_2d_fe1", (DL_FUNC) &_rcpp_module_boot_cpp_pde_2d_fe1, 0},
    {"_rcpp_module_boot_cpp_pde_2d_fe2", (DL_FUNC) &_rcpp_module_boot_cpp_pde_2d_fe2, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_femR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
